### ISSUE TITLE
Lexer Token Types

### ISSUE THREAD

**Issue by abhishekc-sharma** [drewcode/TheCCompiler#1]
We need to decide the various Token Types that our Lexer will produce for various lexemes that we match from the code. We cant really start work until then.

We also need to decide how these tokens are going to be represented in our code. Considering that we are going to use C++ we need to decide if we are going to do it how it would be done in C with structs, enums and unions and just use the convenience of STL provided by C++ to store data or go full on into OOP mode with classes to represent tokens and have a full class hierarchy representing tokens.

**Comment by drewcode** [comment]
already done ?
