### ISSUE TITLE
Add more types of literals

### ISSUE THREAD

**Issue by abhishekc-sharma** [drewcode/TheCCompiler#2]
Overview of various literals:

- [x] Integer
- [x] Double
- [ ] Float
- [ ] Long
- [x] Character (No Escape Sequence Support)
- [ ] Character (With Escape Sequence Support)
- [ ] String (No Escape Sequence Support)
- [ ] String (With Escape Sequence Support)

**Comment by drewcode** [comment]
done as necessary
