### ISSUE TITLE
Initial parser discussions

### ISSUE THREAD

**Issue by abhishekc-sharma** [drewcode/TheCCompiler#5]
We need to decide on a grammar for the language and also the type of parser we are gonna use. I'd say the our options are either Recursive Top Down Parser without backtracking, Non-Recursive Top Down Parser or  Bottom Up Parser of sufficient power to handle our grammar.

**Comment by drewcode** [comment]
We discussed this and I think we have decided upon a Bottom up parser **without** backtracking.

But of course, we will need to perform a _logical backtracking_ of sorts while evaluating which production is to be used
